admin:
    address:
        socket_address:
            address: 0.0.0.0
            port_value: 9901
static_resources:
    listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          generate_request_id: true
                          stat_prefix: internal_http
                          use_remote_address: false
                          codec_type: AUTO
                          
                          http_filters:
                            - name: envoy.filters.http.router
                              typed_config:
                                '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                          
                          route_config:
                              name: internal_api
                            
                              virtual_hosts:
                                - name: internal_virtual_host
                                  domains:
                                    - '*'
                                  routes:
                                    - match:
                                        prefix: /configuration/api
                                      route:
                                        prefix_rewrite: /api
                                        cluster: configuration
                                
        - address:
            socket_address:
                  address: 0.0.0.0
                  port_value: 80
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          upgrade_configs:
                              -   upgrade_type: websocket
                                  enabled: ${GATEWAY_SHOULD_UPGRADE_WEBSOCKETS}
                          generate_request_id: true
                          stat_prefix: ingress_http
                          use_remote_address: true
                          codec_type: AUTO
                          route_config:
                              name: public_api

                              response_headers_to_remove:
                                  - X-Powered-By
                              response_headers_to_add:
                                    # CORS
                                  - append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                    header:
                                        key: Access-Control-Allow-Origin
                                        value: ${ALLOWED_ORIGINS}
                                  -   append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                      header:
                                          key: Access-Control-Allow-Methods
                                          value: "GET, POST, OPTIONS, PATCH, PUT, DELETE"
                                  -   append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                      header:
                                          key: Access-Control-Allow-Headers
                                          value: "DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Range, Authorization, Access-Control-Allow-Origin"
                                  -   append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                      header:
                                          key: Access-Control-Max-Age
                                          value: "1728000"
                                  -   append_action: OVERWRITE_IF_EXISTS_OR_ADD
                                      header:
                                          key: Access-Control-Allow-Credentials
                                          value: "true"

                              virtual_hosts:
                                  - name: external_virtual_host
                                    domains:
                                        - '*'

                                    routes:
                                        # CORS preflight handler
                                        - match:
                                              safe_regex:
                                                  regex: ".*"
                                              headers:
                                                  - name: ":method"
                                                    string_match:
                                                        exact: "OPTIONS"
                                          direct_response:
                                              status: 204

                                        - match:
                                              prefix: /gateway/healthz
                                          direct_response:
                                              status: 200

                                        - match:
                                              prefix: /api/alert
                                          route:
                                              cluster: alerts

                                        -   match:
                                                prefix: /api/user
                                            route:
                                                cluster: users

                                        -   match:
                                                prefix: /api/alert
                                            route:
                                                cluster: alerts

                                        -   match:
                                                prefix: /api/daily
                                            route:
                                                cluster: journal

                                        -   match:
                                                prefix: /api/entry
                                            route:
                                                cluster: journal

                                        -   match:
                                                prefix: /api/goal
                                            route:
                                                cluster: journal

                                        -   match:
                                                prefix: /api/2fa
                                            route:
                                                cluster: identity

                                        -   match:
                                                prefix: /api/2fa
                                            route:
                                                cluster: identity

                                        -   match:
                                                prefix: /api/account
                                            route:
                                                cluster: identity

                                        -   match:
                                                prefix: /api/scopes
                                            route:
                                                cluster: identity

                                        -   match:
                                                prefix: /api/auth
                                            route:
                                                cluster: identity

                                        -   match:
                                                prefix: /api/open-id-connect
                                            route:
                                                cluster: identity

                                        - match:
                                              prefix: /
                                          route:
                                              cluster: frontend

                          http_filters:
                              - name: envoy.filters.http.router
                                typed_config:
                                    '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    clusters:
        - name: frontend
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: ui-service
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: '${FRONTEND_ADDRESS}'
                                      port_value: '${FRONTEND_PORT}'

        - name: identity
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: identity
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: '${IDENTITY_SERVICE_ADDRESS}'
                                      port_value: '${IDENTITY_SERVICE_PORT}'

        - name: journal
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: journal
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: '${JOURNAL_SERVICE_ADDRESS}'
                                      port_value: '${JOURNAL_SERVICE_PORT}'

        - name: alerts
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: alerts
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: '${ALERTS_SERVICE_ADDRESS}'
                                      port_value: '${ALERTS_SERVICE_PORT}'

        - name: users
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: users
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: '${USERS_SERVICE_ADDRESS}'
                                      port_value: '${USERS_SERVICE_PORT}'

        - name: mail
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: mail
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: '${MAIL_SERVICE_ADDRESS}'
                          port_value: '${MAIL_SERVICE_PORT}'
                          
        - name: gdpr
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: gdpr
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: '${GDPR_SERVICE_ADDRESS}'
                          port_value: '${GDPR_SERVICE_PORT}'
                          
        - name: configuration
          connect_timeout: 5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: configuration
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: '${CONFIGURATION_SERVICE_ADDRESS}'
                          port_value: '${CONFIGURATION_SERVICE_PORT}'