global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nest-app'
    static_configs:
      - targets:
          - 'spark-identity-service:9464'
          - 'spark-journal-service:9464'
          - 'spark-alerts-service:9464'
          - 'spark-scheduling-service:9464'
          - 'spark-configuration-service:9464'
          - 'spark-mail-service:9464'
          - 'spark-users-service:9464'
